x-common-config: &common-config
  network_mode: host
  ipc: host
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - ROBOT_MODEL_NAME=${ROBOT_MODEL_NAME:-panther}
    - ROBOT_NAMESPACE=${ROBOT_NAMESPACE:-${ROBOT_MODEL_NAME:-panther}}
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    - HUSARION_ROS_BUILD_TYPE=simulation
    - IGN_IP=127.0.0.1

x-cpu-config: &cpu-config
  env_file: .env.cpu

x-gpu-config: &gpu-config
  runtime: nvidia
  env_file: .env.gpu

services:
  husarion_ugv_gazebo:
    image: husarion/husarion-ugv-gazebo:humble-2.2.2-20250702
    container_name: husarion_ugv_gazebo
    <<:
      - *common-config
      - *gpu-config
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - gps_logs:/ros2_ws/gps_logs
      - ../../free_space_centering:/ros2_ws/src/free_space_centering:ro
      - ../../gps_coordinate_logger:/ros2_ws/src/gps_coordinate_logger:ro
      - ../../husarion_ugv_gazebo/launch/simulation.launch.py:/ros2_ws/install/husarion_ugv_gazebo/share/husarion_ugv_gazebo/launch/simulation.launch.py:ro
      - ../../husarion_ugv/package.xml:/ros2_ws/install/husarion_ugv/share/husarion_ugv/package.xml:ro
      - ../../husarion_ugv_description/config/components.yaml:/ros2_ws/install/husarion_ugv_description/share/husarion_ugv_description/config/components.yaml:ro
      - ../../worlds:/ros2_ws/worlds:ro
    command: >
      bash -lc "apt-get update &&
      apt-get install -y  python3-colcon-common-extensions &&
      source /opt/ros/humble/setup.bash &&
      if [ -f /ros2_ws/src/free_space_centering/package.xml ]; then
        cd /ros2_ws &&
        colcon build --packages-select free_space_centering gps_coordinate_logger &&
        source /ros2_ws/install/setup.bash;
      fi &&
      __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia ros2 launch husarion_ugv_gazebo simulation.launch.py
      gz_world:=${GZ_WORLD:-/ros2_ws/worlds/parking_lot_world_ori.sdf}
      fuse_gps:=True
      localization_mode:=enu
      log_level:=DEBUG"

volumes:
  gps_logs:
    driver: local
